# Generated by Django 3.2 on 2022-08-30 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Oreum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('oreumlevel', models.CharField(choices=[('steep-slope', '경사 심함'), ('easy-slope', '경사 완만')], max_length=30)),
                ('nightview', models.CharField(choices=[('Good-view', '야경 좋음'), ('normal-view', '야경 보통')], max_length=30)),
                ('location', models.CharField(choices=[('Hangyeong-myeon', '한경면'), ('Hallim-eup', '한림읍'), ('Aewol-eup', '애월읍'), ('Jeju-si', '제주시'), ('Jocheon-eup', '조천읍'), ('Gujwa-eup', '구좌읍'), ('Udo-myeon', '우도면'), ('Seongsan-eup', '성산읍'), ('Pyoseon-myeon', '표선면'), ('Namwon-eup', '남원읍'), ('Seogwipo-si', '서귀포시'), ('Andeok-myeon', '안덕면'), ('Daejeong-eup', '대정읍')], max_length=50)),
                ('lat', models.FloatField(null=True)),
                ('lng', models.FloatField(null=True)),
                ('mainphoto', models.ImageField(blank=True, null=True, upload_to='')),
                ('subphoto', models.ImageField(blank=True, null=True, upload_to='')),
                ('published_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('content', models.TextField()),
            ],
        ),
    ]
